name: Render Markdown Files

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  render_markdown:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install pandoc
      run: sudo apt-get install pandoc -y

    - name: Render Markdown files
      run: |
        mkdir rendered_html
        for file in *.md; do
          pandoc "$file" -o "rendered_html/${file%.md}.html"
        done

    - name: Commit rendered HTML files
      uses: EndBug/add-and-commit@v7
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: 'Render Markdown to HTML'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
